### PR TITLE
Advertising and turning hardware on/off

### PR DESCRIPTION
**Pull request by fmatosqg**
Covers #47 

Unfortunately I brought a dependency for permissions that is giving me a bad time when compiling on iOS. Help is appreciated.

Turning hw on/off should work on iOS but so far is untested.
Advertising not implemented on iOS at all.

### CODE REVIEW

**Comment by ravernkoh** [comment]
Any idea when this will be accepted?

**Comment by fmatosqg** [comment]
@ravernkoh I'd like to hear some input from @pauldemarco before working on the conflict solving.

Conflict should be easy to solve.

**Comment by fmatosqg** [comment]
Hi @pauldemarco,

what do you think about this change?

**Comment by nhardt** [comment]
@fmatosqg do you think you will do anything further with this? I attempted to rebase the pull request on HEAD. I was able to get it to compile but I'm getting some run time errors that I believe are related to a dart 1.0 -> 2.0 issue. (Still working on it)

I think in the original development of flutter_blue, features showed up at different times for iOS and android. Would it be cleaner to make a commit that only provides advertising, and only on android?

**Comment by nhardt** [comment]
Just to not leave this open, I was able to get just the advertising portion of this patch applied to HEAD. It does appear that the advertising worked on android, I am able to see an advertised phone in the example app from another phone.

I'm not sure how useful advertising is on it's own. Looks like maybe next step is to be able to set up a device as a bluetooth gatt server. Then maybe you could connect with the existing flutter_blue client code.

**Comment by ram231** [comment]
why the author didn't accept this one?

**Comment by fmatosqg** [comment]
@nhardt

I needed both features when developing for rpi3 for some reason.

**Comment by fvisticot** [comment]
Seems the PR is waiting from several month. Can you please review it and provide a new version ?
Advertising feature is a great feature !

**Comment by zzzh** [comment]
@pauldemarco 
I think the function of turning on/off hardware should be added,  think the below scenario: open a ble app, hardware turned on automatically ( if not yet), close it, hardware turned off automatically (if it was not on before open the app)

**Comment by ride4sun** [comment]
fyi: @boskokg

I am not sure if that solved your problem. If not your could try another branch which ahs some of the fixes applied to it:
change your yaml to :

  flutter_blue:
    git:
      url: https://github.com/boskokg/flutter_blue.git

**Comment by boskokg** [comment]
Please include the ref...

  flutter_blue:
    git:
      url: https://github.com/boskokg/flutter_blue.git
      ref: 0.7.1

**Pull request closed without merging**
