### PR TITLE
add minimum sdk version

### PR DESCRIPTION
**Pull request by lidongze91**
Currently flutter supports a minimum SDK version of 16 and all plugins should be able to match it, anything lower than that will probably cause some unwanted issues. We need to add those into Android Manifest and properly document it.

### CODE REVIEW

**Comment by lidongze91** [comment]
Hi Paul, Could you review this please? Thanks!

**Comment by lidongze91** [comment]
Hi Paul, would you kindly do a review please?

**Comment by pauldemarco** [comment]
Bluetooth low energy was not introduced into the Android SDK until API 18, see here: https://developer.android.com/guide/topics/connectivity/bluetooth-le

**Comment by pauldemarco** [comment]
@mehmetf I’m assuming this means we should at a minimum target API 18 in the plugin, so that user’s projects that try to use FlutterBlue will be instructed to update.

**Comment by mehmetf** [comment]
That's great to know. Yes, this should indeed be 18 then. We are trying to do a sweep of all plugins used internally and make sure their minSDK's are set.

**Comment by mehmetf** [comment]
We will send a separate PR for that. Will also update CHANGELOG and increment version so you can publish.

**Pull request merged**
