### PR TITLE
Build with latest Android Studio and Dart SDK.

### PR DESCRIPTION
**Pull request by kristoffer-zliide**
- [x] Projects that depends on flutter_blue no longer compiles after upgrading to Android Studio 3.2 because of old protobuf dependency,
- [x] Example project no longer builds after upgrading to latest beta flutter because of old intl_translations.
- [x] Projects that depends on other plugins that have migrated to androidx no longer compiles, because the compat code used for permission checks exists both in the old library and in the new androidx library.

### CODE REVIEW

**Comment by pauldemarco** [comment]
Firstly, thanks for your contribution!

This includes too many changes for one PR.

Could you separate the change to `androidx.appcompat:appcompat:1.0.0` into it's own PR?

The other changes are duplicates of existing PR's and I will be applying them once Flutter's official plugin repo has made the change. 

Thanks again!

**Comment by ened** [comment]
Hi @kristoffer-zliide could you please rebase this PR? I believe there are some changes rgd. intl handling which could still be useful

**Comment by kristoffer-zliide** [comment]
@ened: done. Not much left :-) The Intl issue got fixed in 2b6c307. The iOS build issue mentioned in 34c19ba remains though and should be fixed in this PR.

**Comment by pauldemarco** [comment]
@kristoffer-zliide 
Please rebase the ios change onto master and I'll merge it in after testing.

Thanks!

**Comment by kristoffer-zliide** [comment]
I've merged master, however, I'm in doubt about 34c19ba now. We have three macs at the office, and if we do

$ flutter create mycleanproject
$ cd mycleanproject
$ flutter run

the sample app opens fine. If we then add `flutter_blue: ^0.5.0` as a dependency and do

$ flutter packages get
$ flutter run

then on one of the three machines we get the error `.../mycleanproject/Pods/!ProtoCompiler/protoc: No such file or directory` but on the other two, the sample app opens fine again. The path is obviously wrong on the one machine and if i use this fork instead, there is no error. But if I use this fork on the other two machines, they then get the error .../mycleanproject/ios/ios/Pods/!ProtoCompiler/protoc: No such file or directory`

The two machines are dev machines, so in order to work with our code we're now on the official 0.5.0 version, meaning that the third machine can't build our code, which is not good since we intended to use that as a build server, so I'd love to get the issue resolved somehow.

**Comment by pauldemarco** [comment]
@kristoffer-zliide 
Thanks for the report. Please keep me posted if you find anything else out.

**Comment by pauldemarco** [comment]
This should be resolved in the latest version 0.6.3

Thanks for your contribution!

**Pull request closed without merging**
