### PR TITLE
Remove minSdk declaration from AndroidManifest.xml

### LINKED ISSUE #332: Gradle complains about minSdkVersion in AndroidManifest.xml
Gradle complains about minSdkVersion in AndroidManifest.xml:

> ERROR: The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
> Remove minSdkVersion and sync project

* Android Studio 3.4.2
* flutter_blue-0.6.0+2
* Gradle 5.1.1
* Android Gradle Plugin 3.4.2

[√] Flutter (Channel master, v1.8.4-pre.91, on Microsoft Windows [Version 10.0.18950.1000], locale ja-JP)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Android Studio (version 3.4)
[√] Connected device (1 available)

### PR DESCRIPTION
**Pull request by ened**
Fixes #332.

It's sufficient to declare this property in build.gradle now.

### CODE REVIEW

**Comment by ened** [comment]
@pauldemarco do you have time for this issue?

**Comment by boskokg** [comment]
Note:
I added your code together with other merge request.

  flutter_blue:
    git:
      url: https://github.com/boskokg/flutter_blue.git
      ref: 0.7.1

**Comment by GitHub-Vic** [comment]
Hi DeMarco:
why does the class BluetoothDescriptor read() and write(List<int> value)
use the type <int>
can it change the other type?

**Comment by pauldemarco** [comment]
Cherry-picked commit #e1e4abd455ab0f58714a111a3ad56813cb60097b

**Pull request closed without merging**
