### PR TITLE
Queue GATT operations, refactor reply channels

### LINKED ISSUE #30: bluetoothDevice.discoverServices() doesn't return anything
I'm having trouble getting the list of services from a bt device, my snippet:

```
List<BluetoothService> services = await widget.device.discoverServices();
print("success discovered");
```
never gets to print "success", here's what i see in the log:
```
D/FlutterBluePlugin(24804): onServicesDiscovered: 4 sink:null
```

It seems the servicesDiscoveredHandler.onListen function (which registers the servicesDiscoveredSink) is called only after onServicesDiscovered; but i can't find out why.

Maybe some change in the flutter framework? I've tried using alpha channel (2017-12-12) and git from yesterday. This seems to happen with flutter_blue 0.2.3 and git HEAD.

If you can't find time to fix this, any hints would be appreciated to maybe enable me to produce a PR.

### PR DESCRIPTION
**Pull request by dturing**
Bluetooth GATT operations cannot run concurrently, so they must be queued up to let old operations
finish before a new one is triggered.

Also, there is no need for a separate EventChannel for every kind of operation; answers (except for
scanning) are now sent via the plugin's main MethodChannel.

this mostly does #11, and fixes #30

### CODE REVIEW

**Comment by pauldemarco** [comment]
Thanks for the PR. I believe I decided against a queue within the framework, since Dart makes it incredibly easy for async operations, i figured i'd leave that up to the end user.

Also, I'm not sure the implications this would have on the iOS side, since I considered both platforms in parallel as I designed the API.

I'll look into this further.

**Comment by dturing** [comment]
Hi, the thing with moving the async handling to "end-user-space" is that with the current implementation, it's impossible to know when a read or write operation has actually finished. You might get rid of the queue, but you'd still have to wait for the onDescriptorWrite (et al.) to get called before returning from the channel method call, or provide another way to know when the write has actually "hit the air".

**Comment by janekm** [comment]
I do believe this is better handled at the library level:
- iOS handles this at the OS level, so it's not needed there. If the library doesn't handle it, users of the library (such as myself...) will wonder why their code that was working great on iOS falls over horribly on Android.
- It is not simple to handle in the user code; take for example the issue I currently face, where I need to enable notifications in two characteristics in separate services. On iOS, I can iterate over the services with "services.forEach", then when I encounter the right characteristic, enable notifications, and then write to the characteristic that causes the device to start operation. I would have to change the code to multiple phases, one to collect all the characteristics and then a separate one to perform the write / notification operations.

**Comment by pauldemarco** [comment]
Perhaps if you could share a code snippet I could better understand the situation.

I also have much experience with the woes of Android Bluetooth and the problem of no built in queue, which is why I designed most operations in FlutterBlue to return Futures that complete once that operation succeeds.  This way, you can simply `await writeCharacteristic` and be assured the next time it is called, the underlying controller is ready.

**Comment by dfischer23** [comment]
I can't produce a code snippet right now (and its difficult since it will depend on a bt device as you know), but:

No, "await writeCharacteristic" is not enough. Strictly, you probably dont need a queue if you offload the responsibility to the user await-ing each op, but the write op is only finished when onCharacteristicWrite of the associated BluetoothGattCallback is called. If you are writing withResponse, this should be ok since your future is only resolved after onCharacteristicWrite. withoutResponse though, it is resolved instantly (i remember it failing for almost any operation though, at least readCharacteristic, but i can't see that in the code right now), and a second write just after the await will fail.

Have you tried reading a number of characteristics in sequence? I couldnt get that to work at all without introducing some random large delay between my reads. (Yes, i was await-ing the readCharacteristic calls).

My PR solves the issue mainly by delaying the response to the methodChannel function call until the operation has really finished. It also avoids a lot of re-identification (things like
        .where((p) =>
            (p.request.remoteId == request.remoteId) &&
            (p.request.descriptorUuid == request.descriptorUuid) &&
            (p.request.characteristicUuid == request.characteristicUuid) &&
            (p.request.serviceUuid == request.serviceUuid))
), since the reply is directly to the call (which i think is the way a methodChannel should operate).

A queue is the recommended way of handling BT GATT operations on android, and by queuing up a simple operation structure which handles the completion callback, this has the welcome side-effect of making the call/response channels a lot clearer.

Without this, i couldn't get even simple operations to work reliably (see #30). With it, it all works as advertised.

**Comment by dfischer23** [comment]
Hm. Sorry, i see writeCharacteristic always results in a call to the onWriteCharacteristic callback. So i can't, right now, say why your existing way of returning a future to the onWriteCharacteristic wouldn't work for me (i'm *very* sure it didn't though :). I can produce a simple example once i'm back at my usual workplace, next week or so.

**Comment by pauldemarco** [comment]
This was working on my android devices, we would need to investigate your use case.

Here's an example of reading characteristics in a loop, leveraging the power of Dart async await:
```dart
var characteristics = service.characteristics;
for(BluetoothCharacteristic c in characteristics) {
    List<int> value = await device.readCharacteristic(c);
    print(value);
}
```

**Comment by dfischer23** [comment]
That's pretty much what i was doing. I'll try to create a short example that fails for me.

**Comment by dturing** [comment]
Whoops, i see i was using the wrong user name :) dfischer23 == dturing ;)

**Comment by janekm** [comment]
The code that was failing for me looks like this, with some irrelevant code removed:

```dart
        await _H10device.setNotifyValue(_hrCharacteristic, true);
        _hrSubscription = _H10device.onValueChanged(_hrCharacteristic).listen((value) { }
        await _L8device.setNotifyValue(_ppgCharacteristic, true);
        _ppgSubscription = _L8device.onValueChanged(_ppgCharacteristic).listen((value) {}
        await _L8device.setNotifyValue(_ecgCharacteristic, true);
        _ecgSubscription = _L8device.onValueChanged(_ecgCharacteristic).listen((value) { }
        await _L8device.writeCharacteristic(_controlCharacteristic, [0xab, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x19, 0x00, 0x01, 0x01]);
```

Looking through FlutterBluePlugin.java, it appears that setNotifyValue is immediately returning the Response rather than waiting for the write to the descriptor to complete, which explains why this kind of code is failing.

**Comment by dturing** [comment]
Hey @pauldemarco,

with current git i now do:
```
print("Discovering services...");
List<BluetoothService> services = await device.discoverServices();

for(BluetoothService service in services) {
  print("Device service:" + " " + service.uuid.toString() + " " + service.deviceId.toString() + " " + service.isPrimary.toString());
    var characteristics = service.characteristics;
    for(BluetoothCharacteristic c in characteristics) {
        print("Characteristic "+c.uuid.toString());
        List<int> value = await device.readCharacteristic(c);
        print(value);
    }
}
```

and that gives me (consistently):
```
I/flutter (21248): Discovering services...
D/BluetoothGatt(21248): discoverServices() - device: B8:27:EB:FF:BC:C8
I/flutter (21248): NETWORKS: 0
D/BluetoothGatt(21248): onSearchComplete() = Device=B8:27:EB:FF:BC:C8 Status=0
D/FlutterBluePlugin(21248): onServicesDiscovered: 4 sink:io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation@e1b6133
I/flutter (21248): Device service: 00001800-0000-1000-8000-00805f9b34fb B8:27:EB:FF:BC:C8 true
I/flutter (21248): Characteristic 00002a00-0000-1000-8000-00805f9b34fb
I/flutter (21248): remoteId: B8:27:EB:FF:BC:C8 characteristicUuid: 00002a00-0000-1000-8000-00805f9b34fb serviceUuid: 00001800-0000-1000-8000-00805f9b34fb
D/FlutterBluePlugin(21248): onCharacteristicRead: 
I/flutter (21248): [114, 97, 100, 105, 111]
I/flutter (21248): Characteristic 00002a01-0000-1000-8000-00805f9b34fb
I/flutter (21248): remoteId: B8:27:EB:FF:BC:C8 characteristicUuid: 00002a01-0000-1000-8000-00805f9b34fb serviceUuid: 00001800-0000-1000-8000-00805f9b34fb
D/FlutterBluePlugin(21248): onCharacteristicRead: 
I/flutter (21248): [128, 0]
I/flutter (21248): Device service: 00001801-0000-1000-8000-00805f9b34fb B8:27:EB:FF:BC:C8 true
I/flutter (21248): Characteristic 00002a05-0000-1000-8000-00805f9b34fb
I/flutter (21248): remoteId: B8:27:EB:FF:BC:C8 characteristicUuid: 00002a05-0000-1000-8000-00805f9b34fb serviceUuid: 00001801-0000-1000-8000-00805f9b34fb
E/flutter (21248): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (21248): PlatformException(read_characteristic_error, unknown reason, may occur if readCharacteristic was called before last read finished., null)
E/flutter (21248): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:502)
E/flutter (21248): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154)
E/flutter (21248): <asynchronous suspension>
E/flutter (21248): #2      BluetoothDevice.readCharacteristic (package:flutter_blue/src/bluetooth_device.dart:56)
E/flutter (21248): <asynchronous suspension>
E/flutter (21248): #3      _DevicePageState.initState.<anonymous closure> (file:///home/dan/src/exp/kitchen.fm/bluetooth-control-app/radio_control/lib/device_page.dart:133)
E/flutter (21248): <asynchronous suspension>
E/flutter (21248): #4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
E/flutter (21248): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
E/flutter (21248): #6      _DelayedData.perform (dart:async/stream_impl.dart:578)
E/flutter (21248): #7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694)
E/flutter (21248): #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
E/flutter (21248): #9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter (21248): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
```

**Comment by pauldemarco** [comment]
@dturing Just confirming, you're seeing this even after closing #30?

**Comment by dturing** [comment]
@pauldemarco, yes.

**Comment by lchinke** [comment]
anything new about this issue? I asked for help about this here: https://stackoverflow.com/questions/51310233/platformexception-trying-to-readcharacteristic-on-flutter-blue

**Comment by kentcb** [comment]
Just a thought: I suspect the error message may be a red herring. I had exactly the same thing an hour or so ago when I took the sample code and tried it against a device. The thing is, not all characteristics are readable. I changed it to:

```dart
  for (final c in characteristics) {
    if (c.properties.read) {
      // do read here
    } else {
      debugPrint("  cannot read");
    }
  }
```
And it worked. Assuming I'm right (a big assumption because I'm no BT expert), I think these two things should happen:

1. The error you get when reading a non-readable characteristic should be improved. Probably same for writing to non-writable.
2. The docs/readme should be improved to stop people falling into this trap.

**Comment by justinwyer** [comment]
@kentcb has a point, once I excluded characteristics that do not support read there were no more errors.

**Comment by dturing** [comment]
I'm positive that my problem wasn't caused by trying to read characteristics that aren't readable.

The project i wanted to use flutter_blue for is currently dormant, so i haven't followed this further. I'm willing to invest more time in this PR (or split it up, since it's really two things at once) if it stands a chance of being merged. @pauldemarco maybe we can meet up somewhere w/ chat to discuss?

**Comment by pauldemarco** [comment]
Hi @dturing,

Hope all is well. The latest version of the plugin had some major breaking changes. If you get a chance to try it out in a project and still experience the issue, please let me know.

I'll be closing this PR for now.

**Pull request closed without merging**
