### PR TITLE
Update rxdart to ^0.27.0

### PR DESCRIPTION
**Pull request by petoknm**

### CODE REVIEW

**Comment by michael-golfi** [comment]
Is there anything else required for getting this merged? We have a conflict with our dependencies as well

**Comment by petoknm** [comment]
@pauldemarco ^

**Comment by nickwwh** [comment]
fixes #866

**Comment by bardram** [comment]
Could we get this released? Having conflicts in dependencies..... 

@pauldemarco

**Comment by peekpt** [comment]
Use this fork https://github.com/pauldemarco/flutter_blue/issues/929#issuecomment-930759129

**Pull request closed without merging**
