### PR TITLE
Update flutter_blue.podspec to fix iOS build error

### PR DESCRIPTION
**Pull request by NaelAwayes**
The path lacked for protoc lacked '/ios/' which caused Xcode build to fail.

Fixes issue #82

### CODE REVIEW

**Comment by PiotrWpl** [comment]
@NaelAwayes @pauldemarco 
For me changing:
`protoc = ENV['PWD'] + '/Pods/!ProtoCompiler/protoc`'
to
`protoc = ENV['PWD'] + '/ios/Pods/!ProtoCompiler/protoc`'
helps.

Not a
`protoc = ENV['PWD'] + 'ios/Pods/!ProtoCompiler/protoc'`
like it was in pull request. You missed one "/" (slash) before "ios" directory

**Comment by NaelAwayes** [comment]
Thanks for those precisions, will test when I get home.

**Comment by PiotrWpl** [comment]
Hi @NaelAwayes ,

any update on that?

Cheers,

**Comment by bsheen** [comment]
@pauldemarco any chance we can get the merged in?

**Comment by pauldemarco** [comment]
CLA is not signed.

Also, using the latest xcode this fix wasn't needed for me.  If someone could supply me with reference to why this is needed, I will get it merged right away.

**Comment by bsheen** [comment]
For anyone else reading this, I'm getting this error when executing `pod install` directly, as for the `pod` command to pick up the `Podfile` we need to be in the `ios` folder. Hence `ENV['PWD']` puts the path out.

**Comment by bsheen** [comment]
I've done some further digging on this one, at some point (not exactly sure of the commit) the workingDir changed in the Flutter tooling e.g.
Was `workingDirectory: bundle.path` as per [this line](https://github.com/flutter/flutter/blob/20004357288389829df79a3af5308d4c5819aecf/packages/flutter_tools/lib/src/ios/cocoapods.dart#L172)
Is now `workingDirectory: iosProject.hostAppRoot.path` as per [this line](https://github.com/flutter/flutter/blob/2d3ff10d62a1f1fdcbdbe92cbcc5a5594f95d500/packages/flutter_tools/lib/src/ios/cocoapods.dart#L226)
Potentially `processManager` is executing the `pods` process in the `ios` folder but this isn't being reflected in the `$PWD` environment variable?

**Comment by malleusinferni** [comment]
Elaborating on [my previous comment](https://github.com/pauldemarco/flutter_blue/issues/108#issuecomment-455931209) in #108:

Relying on the `PWD` environment variable during podspec evaluation seems to be a bad idea. Cocoapods uses the `PODS_ROOT` variable to point to the pod installation directory. This doesn't necessarily have anything to do with `PWD`, which can apparently change on a per-project basis, such as when projects were originally created by different versions of Flutter. As such, any use of `ENV['PWD']` in the podspec file should be avoided. The path to a file in another pod should begin with `PODS_ROOT`.

Note that Cocoapods *does* set the `PWD` env var of a subshell to a pod's root directory when evaluating the `prepare_command` script, so in that context it should be fine to use `.` or `$PWD` to refer to paths inside the pod directory. It looks like that's the `ios` subdirectory under the FlutterBlue root.

I can't yet tell if there's a strictly less fragile way to run a build command like this. Perhaps reaching out to the Cocoapods project for support is in order.

**Comment by bsheen** [comment]
I can confirm that @malleusinferni's fix as originally suggested in a (comment)[https://github.com/pauldemarco/flutter_blue/issues/108#issuecomment-455931209] on #108 does fix this issue.

**Comment by bsheen** [comment]
@pauldemarco I've opened a new (PR)[https://github.com/pauldemarco/flutter_blue/pull/195] in line with the above comments from @malleusinferni and myself (In my opinion it supersedes this one).

**Comment by ferryirawan** [comment]
Error output from CocoaPods:
↳
       /bin/bash: line 3: /Users/ferry/Documents/Hybrid/Shop: No such file or directory

Still got error, how did to fix this issue ?

**Comment by NaelAwayes** [comment]
Hello,
Definitely not the same issue. It seems you mistyped something when configuring your project, or the error log you provided is incomplete.

**Comment by ferryirawan** [comment]
Hello @NaelAwayes I try to run pod install.. i got error like this.
Using Terminal Android Studio :
    -> Installing !ProtoCompiler (3.8.0)
      > Copying !ProtoCompiler from `/Users/ferry/Library/Caches/CocoaPods/Pods/Release/!ProtoCompiler/3.8.0-7fc49` to `Pods/!ProtoCompiler`

    -> Installing Flutter (1.0.0)

    -> Installing MTBBarcodeScanner (5.0.11)
      > Copying MTBBarcodeScanner from `/Users/ferry/Library/Caches/CocoaPods/Pods/Release/MTBBarcodeScanner/5.0.11-f453b` to `Pods/MTBBarcodeScanner`

    -> Installing Protobuf (3.9.0)
      > Copying Protobuf from `/Users/ferry/Library/Caches/CocoaPods/Pods/Release/Protobuf/3.9.0-1097c` to `Pods/Protobuf`

    -> Installing barcode_scan (0.0.1)

    -> Installing flutter_blue (0.0.1)
     > Running prepare command
       $ /bin/bash -c  set -e mkdir -p gen /Users/ferry/Documents/Hybrid/Shop And Go Flutter/ios/Pods/!ProtoCompiler/protoc         --objc_out=gen         --proto_path=../protos
       ../protos/*.proto
    [!] /bin/bash -c 
    set -e
    mkdir -p gen
    /Users/ferry/Documents/Hybrid/Shop And Go Flutter/ios/Pods/!ProtoCompiler/protoc         --objc_out=gen         --proto_path=../protos         ../protos/*.proto

    /bin/bash: line 3: /Users/ferry/Documents/Hybrid/Shop: No such file or directory

    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/executable.rb:69:in `execute_command'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/executable.rb:27:in `block in executable'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/pod_source_preparer.rb:66:in `block (2 levels) in run_prepare_command'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/pod_source_preparer.rb:60:in `chdir'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/pod_source_preparer.rb:60:in `block in run_prepare_command'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/pod_source_preparer.rb:59:in `run_prepare_command'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/pod_source_preparer.rb:37:in `prepare!'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/pod_source_installer.rb:63:in `install!'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:426:in `install_source_of_pod'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:377:in `block (2 levels) in install_pod_sources'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/user_interface.rb:86:in `titled_section'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:376:in `block in install_pod_sources'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:359:in `each'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:359:in `install_pod_sources'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:189:in `block in download_dependencies'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:188:in `download_dependencies'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:137:in `install!'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/command/install.rb:48:in `run'
    /Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.6.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳
       /bin/bash: line 3: /Users/ferry/Documents/Hybrid/Shop: No such file or directory

Error running pod install

Using Terminal in Mac :

-> Installing flutter_blue (0.0.1)
     > Running prepare command
       $ /bin/bash -c  set -e mkdir -p gen /flutter_project/Pods/!ProtoCompiler/protoc         --objc_out=gen         --proto_path=../protos         ../protos/*.proto
    [!] /bin/bash -c
    set -e
    mkdir -p gen
    /flutter_project/Pods/!ProtoCompiler/protoc         --objc_out=gen         --proto_path=../protos         ../protos/*.proto

    /bin/bash: line 3: /flutter_project/Pods/!ProtoCompiler/protoc: No such file or directory

different for this issue [This is a link to comment help](https://github.com/pauldemarco/flutter_blue/issues/108) ?

**Comment by NaelAwayes** [comment]
@ferryirawan My guess is that your Flutter project folder is named "Shop And Go", which contains spaces and is not managed properly on build. That's why you get that error : 

` /bin/bash: line 3: /Users/ferry/Documents/Hybrid/Shop: No such file or directory`

You should remove spaces for your folder name and hopefully that fixes it.

**Comment by ferryirawan** [comment]
@NaelAwayes  thank you so much, it is working..
in my case, I tried removing spaces in the folder name, and I changed
protoc = ENV['PWD'] + '/ios/Pods/!ProtoCompiler/protoc'
to
protoc = ENV['PWD'] + '/Pods/!ProtoCompiler/protoc'

**Pull request closed without merging**
