### PR TITLE
modify connect Android SDK version >= 23

### PR DESCRIPTION
**Pull request by 123lxw123**
### What's wrong  
Connect fail with error state 133 when Android version >= 23 (Android M).
### How to resolve
[stackoverflow answer](https://stackoverflow.com/questions/25330938/android-bluetoothgatt-status-133-register-callback)  
I do it and it work.

### CODE REVIEW

**Comment by mainini** [comment]
This looks like the same issue as in #219

**Comment by 123lxw123** [comment]
I see it just now, but it forgets to consider Android version.

**Comment by mainini** [comment]
Agree. I was not aware of the version dependency. I closed #219 ...

**Comment by pauldemarco** [comment]
Confirmed that this fixed an issue on an older LG phone.

**Pull request merged**
