### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nicolasdupere**
Add setup info in README.md.

Can close:

Issues #539
Issues #542
Maybe #332
Maybe #28

### CODE REVIEW

**Comment by reteps** [comment]
This would be great, I was very confused.

**Comment by nicolasdupere** [comment]
Thanks

**Comment by ened** [comment]
@pauldemarco possible to merge?

**Comment by dwchiang** [comment]
This is useful setup info in `README.md` 👍

**Pull request merged**
